# -*- coding: utf-8 -*-
"""lab5.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1swMQOaPajLICWYX8w7VbzejJSbQEzsfn
"""

answernum = 0
answer = 0
for answernum in range(0,3):
  answer = answer + int(input("Enter a number "))
  answernum = answernum + 1
print(answer/3)

num = int(input("Please enter a number: "))

while num > 1:
  num = num/2
  print(num)